const listWordData= [
    { id:1 , word:'ありがとうございます' , hira: 'ありがとうございます' ,mean:'Cảm ơn ' , miss:false , level:0 },
    { id:2 , word:'車' , hira: 'くるま' ,mean:'Xe hơi' , miss:false , level:0  },
    { id:3 , word:'野菜' , hira: 'やさい' ,mean:'Rau' , miss:true , level:1  },
    { id:4 , word:'指輪' , hira: 'ゆびわ' ,mean:'Nhẫn' , miss:true , level:2  },
    { id:5 , word:'鍋' , hira: 'なべ' ,mean:'Nồi' , miss:false , level:3 },
    { id:6 , word:'果物' , hira: 'くだもの' ,mean:'Hoa quả' , miss:true , level:4 },
    { id:7 , word:'ミカン' , hira: 'みかん' ,mean:'Quả quýt' , miss:false , level:5 },  
    { id:8 , word:'家' , hira: 'いえ' ,mean:'Nhà' , miss:false , level:0 }, 
    { id:9 , word:'病院' , hira: 'びょういん' ,mean:'Bệnh viện' , miss:false , level:1 },
    { id:10 , word:'漢字' , hira: 'かんじ' ,mean:'Hán tự' , miss:false , level:5 },
    { id:11 , word:'家庭' , hira: 'かてい' ,mean:'Gia đình' , miss:false , level:0 },
    { id:12 , word:'経済' , hira: 'けいざい' ,mean:'kinh tế' , miss:false , level:4 },
    { id:13 , word:'庭' , hira: 'にわ' ,mean:'Vườn' , miss:false , level:4 },
    { id:14 , word:'大学' , hira: 'だいがく' ,mean:'Đại học' , miss:false , level:0 },
    { id:15 , word:'研究者' , hira: 'けんきゅうしゃ' ,mean:'Nhà nghiên cứu' , miss:false , level:1 },
    { id:16 , word:'電気' , hira: 'でんき' ,mean:'Điện, đèn điện' , miss:false , level:1 },
    { id:17 , word:'私' , hira: 'わたし' ,mean:'Tôi' , miss:false , level:0 },
    { id:18 , word:'皆さん' , hira: 'みなさん' ,mean:'Mọi người' , miss:false , level:0 },
    { id:19 , word:'先生' , hira: 'せんせい' ,mean:'Thầy/cô' , miss:false , level:0 },
    { id:20 , word:'学生' , hira: 'がくせい' ,mean:'Học sinh, sinh viên' , miss:false , level:0 },
    { id:21 , word:'医者' , hira: 'いしゃ' ,mean:'Bác sĩ' , miss:false , level:0 },
    { id:22 , word:'社員' , hira: 'しゃいん' ,mean:'Nhân viên công ty' , miss:false , level:0 },
    { id:23 , word:'教師' , hira: 'きょうし' ,mean:'Giáo viên' , miss:false , level:1 },
    { id:24 , word:'韓国' , hira: 'かんこく' ,mean:'Hàn Quốc' , miss:false , level:1 },
    { id:25 , word:'中国' , hira: 'ちゅうごく' ,mean:'Trung Quốc' , miss:false , level:1 },
    { id:26 , word:'ベトナム' , hira: 'べとなむ' ,mean:'Việt Nam' , miss:false , level:2 },
    { id:27 , word:'銀行' , hira: 'ぎんこう' ,mean:'Ngân hàng' , miss:false , level:1 },
    { id:28 , word:'本' , hira: 'ほん' ,mean:'Sách' , miss:false , level:0 },
    { id:29 , word:'鉛筆' , hira: 'えんぴつ' ,mean:'Bút chì' , miss:false , level:4 },
    { id:30 , word:'時計' , hira: 'とけい' ,mean:'Đồng hồ' , miss:false , level:0 },
    { id:31 , word:'傘' , hira: 'かさ' ,mean:'Ô, dù' , miss:false , level:0 },
    { id:32 , word:'自動車' , hira: 'じどうしゃ' ,mean:'Xe hơi' , miss:false , level:0 },
    { id:33 , word:'自転車' , hira: 'じてんしゃ' ,mean:'Xe đạp' , miss:false , level:0 },
    { id:34 , word:'雑誌' , hira: 'ざっし' ,mean:'Tạp chí' , miss:false , level:1 },
    { id:35 , word:'手帳' , hira: 'てちょう' ,mean:'Sổ tay' , miss:false , level:1 },
    { id:36 , word:'名刺' , hira: 'めいし' ,mean:'Danh thiếp' , miss:false , level:1 },
    { id:37 , word:'辞書' , hira: 'じしょ' ,mean:'Từ điển' , miss:false , level:1 },    
    { id:38 , word:'英語' , hira: 'えいご' ,mean:'Tiếng Anh' , miss:false , level:1 },
    { id:39 , word:'映画' , hira: 'えいが' ,mean:'Phim' , miss:false , level:1 },
    { id:40 , word:'日本語' , hira: 'にほんご' ,mean:'Tiếng Nhật' , miss:false , level:1 },
    { id:41 , word:'新聞' , hira: 'しんぶん' ,mean:'Báo' , miss:false , level:1 },
    { id:42 , word:'教室' , hira: 'きょうしつ' ,mean:'Lớp học, phòng học' , miss:false , level:2 },
    { id:43 , word:'食堂' , hira: 'しょくどう' ,mean:'Nhà ăn' , miss:false , level:1 },
    { id:44 , word:'事務所' , hira: 'じむしょ' ,mean:'Văn phòng' , miss:false , level:2 },
    { id:45 , word:'会議室' , hira: 'かいぎしつ' ,mean:'Phòng họp' , miss:false , level:1 },
    { id:46 , word:'受付' , hira: 'うけつけ' ,mean:'Bộ phận tiếp tân' , miss:false , level:3 },
    { id:47 , word:'部屋' , hira: 'へや' ,mean:'Căn phòng' , miss:false , level:0 },
    { id:48 , word:'階段' , hira: 'かいだん' ,mean:'Cầu thang' , miss:false , level:1 },
    { id:49 , word:'会社' , hira: 'かいしゃ' ,mean:'Công ty' , miss:false , level:1 },
    { id:50 , word:'お国' , hira: 'おくに' ,mean:'Đất nước' , miss:false , level:2 },
    { id:51 , word:'電話' , hira: 'でんわ' ,mean:'Điện thoại' , miss:false , level:3 },
    { id:52 , word:'靴' , hira: 'くつ' ,mean:'Giầy' , miss:false , level:1 },
    { id:53 , word:'靴下' , hira: 'くつした' ,mean:'Tất, bít tất' , miss:false , level:3 },
    { id:54 , word:'地下' , hira: 'ちか' ,mean:'Tầng hầm, dưới mặt đất' , miss:false , level:1 },
    { id:55 , word:'百' , hira: 'ひゃく' ,mean:'Trăm' , miss:false , level:0 },
    { id:56 , word:'千' , hira: 'せん' ,mean:'Nghìn' , miss:false , level:0 },
    { id:57 , word:'万' , hira: 'まん' ,mean:'Vạn, mười nghìn' , miss:false , level:0 },
    { id:58 , word:'眼鏡' , hira: 'めがね' ,mean:'Kính mắt' , miss:false , level:6 },
    { id:59 , word:'服' , hira: 'ふく' ,mean:'Quần áo' , miss:false , level:1 },
    { id:60 , word:'化粧品' , hira: 'けしょうひん' ,mean:'Mỹ phẩm, đồ hóa trang' , miss:false , level:6 },
    { id:61 , word:'家具' , hira: 'かぐ' ,mean:'Dụng cụ gia đình' , miss:false , level:5 },
    { id:62 , word:'食料' , hira: 'しょくりょう' ,mean:'Lương thực' , miss:false , level:5 },
    { id:63 , word:'駐車場' , hira: 'ちゅうしゃじょう' ,mean:'Bãi đỗ xe' , miss:false , level:4 },
    { id:64 , word:'起きる' , hira: 'おきる' ,mean:'Dậy, thức dậy' , miss:false , level:2 },
    { id:65 , word:'寝る' , hira: 'ねる' ,mean:'Ngủ, đi ngủ' , miss:false , level:2 },
    { id:66 , word:'働く' , hira: 'はたらく' ,mean:'Làm việc' , miss:false , level:2 },
    { id:67 , word:'休む' , hira: 'やすむ' ,mean:'Nghỉ, nghỉ ngơi' , miss:false , level:2 },
    { id:68 , word:'勉強' , hira: 'べんきょう' ,mean:'Học' , miss:false , level:2 },
    { id:69 , word:'終わる' , hira: 'おわる' ,mean:'Hết, kết thúc, xong' , miss:false , level:1 },
    { id:70 , word:'郵便局' , hira: 'ゆうびんきょく' ,mean:'Bưu điện' , miss:false , level:2 },
    { id:71 , word:'図書館' , hira: 'としょかん' ,mean:'Thư viện' , miss:false , level:2 },
    { id:72 , word:'美術館' , hira: 'びじゅつかん' ,mean:'Bảo tàng mỹ thuật' , miss:false , level:2 },
    { id:73 , word:'今' , hira: 'いま' ,mean:'Bây giờ' , miss:false , level:1 },
    { id:74 , word:'半' , hira: 'はん' ,mean:'Một nửa' , miss:false , level:1 },
    { id:75 , word:'午前' , hira: 'ごぜん' ,mean:'Trước 12 giờ trưa, sáng' , miss:false , level:1 }
];


module.exports.listWordData= listWordData;