const listWordData= [
    { id:1 , word:'ありがとうございます' ,mean:'Cảm ơn ' , miss:false , level:0 },
    { id:2 , word:'車' ,mean:'Xe hơi' , miss:false , level:0  },
    { id:3 , word:'野菜' ,mean:'Rau' , miss:true , level:1  },
    { id:4 , word:'指輪' ,mean:'Nhẫn' , miss:true , level:2  },
    { id:5 , word:'なべ' ,mean:'Nồi' , miss:false , level:3 },
    { id:6 , word:'果物' ,mean:'Hoa quả' , miss:true , level:4 },
    { id:7 , word:'ミカン' ,mean:'Quả quýt' , miss:false , level:5 },  
    { id:8 , word:'家' ,mean:'Nhà' , miss:false , level:0 }, 
    { id:9 , word:'病院' ,mean:'Bệnh viện' , miss:false , level:1 },
    { id:10 , word:'漢字' ,mean:'Hán tự' , miss:false , level:5 },
    { id:11 , word:'家庭' ,mean:'Gia đình' , miss:false , level:0 },
    { id:12 , word:'経済' ,mean:'kinh tế' , miss:false , level:4 },
    { id:13 , word:'庭' ,mean:'Vườn' , miss:false , level:4 },
    { id:14 , word:'大学' ,mean:'Đại học' , miss:false , level:0 },
    { id:15 , word:'研究者' ,mean:'Nhà nghiên cứu' , miss:false , level:1 },
    { id:16 , word:'電気' ,mean:'Điện, đèn điện' , miss:false , level:1 },
    { id:17 , word:'私' ,mean:'Tôi' , miss:false , level:0 },
    { id:18 , word:'皆さん' ,mean:'Mọi người' , miss:false , level:0 },
    { id:19 , word:'先生' ,mean:'Thầy/cô' , miss:false , level:0 },
    { id:20 , word:'学生' ,mean:'Học sinh, sinh viên' , miss:false , level:0 },
    { id:21 , word:'医者' ,mean:'Bác sĩ' , miss:false , level:0 },
    { id:22 , word:'社員' ,mean:'Nhân viên công ty' , miss:false , level:0 },
    { id:23 , word:'教師' ,mean:'Giáo viên' , miss:false , level:1 },
    { id:24 , word:'韓国' ,mean:'Hàn Quốc' , miss:false , level:1 },
    { id:25 , word:'中国' ,mean:'Trung Quốc' , miss:false , level:1 },
    { id:26 , word:'ベトナム' ,mean:'Việt Nam' , miss:false , level:2 },
    { id:27 , word:'銀行' ,mean:'Ngân hàng' , miss:false , level:1 },
    { id:28 , word:'本' ,mean:'Sách' , miss:false , level:0 },
    { id:29 , word:'鉛筆' ,mean:'Bút chì' , miss:false , level:4 },
    { id:30 , word:'時計' ,mean:'Đồng hồ' , miss:false , level:0 },
    { id:31 , word:'傘' ,mean:'Ô, dù' , miss:false , level:0 },
    { id:32 , word:'自動車' ,mean:'Xe hơi' , miss:false , level:0 },
    { id:33 , word:'自転車' ,mean:'Xe đạp' , miss:false , level:0 },
    { id:34 , word:'雑誌' ,mean:'Tạp chí' , miss:false , level:1 },
    { id:35 , word:'手帳' ,mean:'Sổ tay' , miss:false , level:1 },
    { id:36 , word:'名刺' ,mean:'Danh thiếp' , miss:false , level:1 },
    { id:37 , word:'辞書' ,mean:'Từ điển' , miss:false , level:1 },    
    { id:38 , word:'英語' ,mean:'Tiếng Anh' , miss:false , level:1 },
    { id:39 , word:'映画' ,mean:'Phim' , miss:false , level:1 },
    { id:40 , word:'日本語' ,mean:'Tiếng Nhật' , miss:false , level:1 },
    { id:41 , word:'' ,mean:'' , miss:false , level: },
    { id:42 , word:'' ,mean:'' , miss:false , level: },
    { id:43 , word:'' ,mean:'' , miss:false , level: },
    { id:44 , word:'' ,mean:'' , miss:false , level: },
    { id:45 , word:'' ,mean:'' , miss:false , level: },
    { id:46 , word:'' ,mean:'' , miss:false , level: },
    { id:47 , word:'' ,mean:'' , miss:false , level: },
    { id:48 , word:'' ,mean:'' , miss:false , level: },
    { id:49 , word:'' ,mean:'' , miss:false , level: },
    { id:50 , word:'' ,mean:'' , miss:false , level: },
    { id:51 , word:'' ,mean:'' , miss:false , level: }
];


module.exports.listWordData= listWordData;